apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
    - image: nekonex/test
      jib:
        args:
          - "-DskipTests"
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - k8s/common.yaml
      - k8s/dev/deployment.yaml