apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  labels:
    app: test
    monitor: test
data:
  application.yaml: |-
    endpoints:
      health:
        details-visible: ANONYMOUS
    mongodb:
      database: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: nekonex/test
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: test
  type: NodePort